# config files
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
#cluster-status: "slurm-status.py"

# resource defaults
max-jobs-per-second: "1"
max-status-checks-per-second: "1"
restart-times: "0"
local-cores: 1
latency-wait: "60"
printshellcmds: True
use-conda: "False"
use-singularity: "False"

