cluster-cancel: "scancel"
restart-times: "1"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"

max-jobs-per-second: "1"
max-status-checks-per-second: "1"
local-cores: 1
latency-wait: "60"
use-conda: "True"
use-singularity: "False"
jobs: "500"
printshellcmds: "True"

